permalink                : pretty

url                      : https://xen0vas.github.io
baseurl                  : "https://xen0vas.github.io"
locale                   : "en-US"
title                    : "Tech Blog about CyberSecurity"
title_separator          : "-"
name                     : "Xenofon Vassilakopoulos Blog"
description              : "Cyber Security and Technical WriteUps"
repository               : "xen0vas/xen0vas.github.io" 
teaser                   : "/assets/images/minimal-dark-hacker-wallpapers.png" 

og_image                 : "/assets/images/minimal-dark-hacker-wallpapers.png"

sass:
    sass_dir:           _sass
    style:              compressed

author:
    name:               xen0vas
    url:
    email:              xenofonv@gmail.com

version:                1.00
github:
repo:                   https://github.com/xen0vas/

pages_list:
    posts:              '/posts'

# EOF
